### ISSUE TITLE
Work with Claude to enable new PIWIK user for CASNotes Community

### ISSUE THREAD

**Issue by vaughangl** [USStateDept/analytics#48]

**Comment by concolato** [comment]
Do you still need help with this Gary?

**Comment by vaughangl** [comment]
Claude,
Yes, as per the email I sent earlier today...if you have a chance,
Thanks,
Gary

**Comment by concolato** [comment]
The site has already been provisioned for Piwik. It looks like we just needed to add the users in your email. This has been done and the users have been informed. Thanks.
